### ISSUE TITLE
Broken tests: ScriptIsInjected_ForNetCoreApp20_Portable et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AzureIntegration#171]
These tests [fail](http://aspnetci/viewLog.html?buildId=432811&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on Ubuntu.

```
System.TimeoutException : The operation at C:\b\w\33bdfc1cae7b2a38\modules\Hosting\src\Microsoft.AspNetCore.Server.IntegrationTesting\Deployers\SelfHostDeployer.cs:173 timed out after reaching the limit of 600000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.StartSelfHostAsync(Uri hintUrl)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync()
   at ApplicationInsightsJavaScriptSnippetTest.JavaScriptSnippetTest.JavaScriptSnippetInjectionTestSuite(String targetFramework, ApplicationType applicationType) in /_/test/ApplicationInsights.HostingStartup.Tests/JavaScriptSnippetTest.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-03-27T21:13:07] TestLifetime Information: Starting test ApplicationInsightsJavaScriptSnippetTest_Portable
| [2018-03-27T21:13:07] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [2018-03-27T21:13:07] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=JavaScript
| [2018-03-27T21:13:07] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "/mnt/temp/buildTmp/334eba48-cbd3-4e8d-8595-11178f334437" --framework netcoreapp2.0 --configuration Release --no-restore 
| [2018-03-27T21:13:08] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.66.2115 for .NET Core
| [2018-03-27T21:13:08] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2018-03-27T21:13:08] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
| [2018-03-27T21:13:10] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.ApplicationInsights.HostingStartup -> /mnt/work/33bdfc1cae7b2a38/modules/AzureIntegration/src/Microsoft.AspNetCore.ApplicationInsights.HostingStartup/bin/Release/netcoreapp2.0/Microsoft.AspNetCore.ApplicationInsights.HostingStartup.dll
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationInsightsHostingStartupSample -> /mnt/work/33bdfc1cae7b2a38/modules/AzureIntegration/sample/ApplicationInsightsHostingStartupSample/bin/Release/netcoreapp2.0/ApplicationInsightsHostingStartupSample.dll
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationInsightsHostingStartupSample -> /mnt/work/33bdfc1cae7b2a38/modules/AzureIntegration/sample/ApplicationInsightsHostingStartupSample/bin/Release/netcoreapp2.0/ApplicationInsightsHostingStartupSample.Views.dll
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationInsightsHostingStartupSample -> /mnt/temp/buildTmp/334eba48-cbd3-4e8d-8595-11178f334437/
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /mnt/temp/buildTmp/334eba48-cbd3-4e8d-8595-11178f334437/ApplicationInsightsHostingStartupSample.dll --server.urls http://localhost:36004/  --server Microsoft.AspNetCore.Server.Kestrel
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=JavaScript
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.ApplicationInsights.HostingStartup
| [2018-03-27T21:13:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 61541
| [2018-03-27T21:23:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Attempting to cancel process 61541
| [2018-03-27T21:23:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Unable to terminate the host process with process Id '61541
| [2018-03-27T21:23:11] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '603.8764548' seconds
| [2018-03-27T21:23:11] TestLifetime Information: Finished test ApplicationInsightsJavaScriptSnippetTest_Portable in 603.9055048s
```

Check out the test history [here](http://aspnetci/project.html?tab=testDetails&testNameId=7623972375749052175&projectId=XPlat&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
@muratg could we prioritize this one? It fails 100% of the time on our Ubuntu agents now, so it should be easy to repro.

**Comment by muratg** [comment]
@pakrym assigned to you. Not sure why the test runs on Ubuntu?

**Comment by pakrym** [comment]
Yep, had the same question. I'll look into it.

**Comment by muratg** [comment]
@pakrym status? Disabled on Ubuntu?

**Comment by pakrym** [comment]
No, I merged a bunch of Console.WriteLines but build was broken over the night so I'm waiting for a test run.

**Comment by natemcmaster** [comment]
Still broken on all 2.0.x builds. The deployer log shows this in the logs

```
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 9913
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: dotnet stderr: Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/home/aspnetagent/aspnetci' is denied. ---> System.IO.IOException: Permission denied
```

**Comment by pakrym** [comment]
I'll look into 2.0.x failures, it's a different one.
